import {hebrewTeam} from './names';
import legionnaires from './legionnaires-roster.json';
import type { Match, League, Favorite, AlertItem } from './types';
export const clubs = [ ['barcelona','ברצלונה'],['madrid','ריאל מדריד'],['haifa','מכבי חיפה'],['telaviv','מכבי תל אביב'],['arsenal','ארסנל'],['liverpool','ליברפול'],['bayern','באיירן מינכן'],['inter','אינטר'],['dortmund','דורטמונד'],['beersheva','הפועל באר שבע'],['beitar','בית״ר ירושלים'],['netanya','מכבי נתניה'],['ashdod','מ.ס. אשדוד'] ];
export const demoLeagues: League[] = [{id:'israel',name:'ליגת העל',country:'Israel',season:'2026/27'},{id:'champions',name:'ליגת האלופות',country:'Europe',season:'2026/27',format:'Cup'},{id:'england',name:'פרמייר ליג',country:'England',season:'2026/27'},{id:'spain',name:'לה ליגה',country:'Spain',season:'2026/27'},{id:'germany',name:'בונדסליגה',country:'Germany',season:'2026/27'},{id:'world',name:'גביע העולם',country:'World',season:'2026'}];
export const demoFavorites: Favorite[] = clubs.slice(0,4).map(([id,name])=>({id,name,kind:'team'}));
const dateNow=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function game(id:string,home:string,away:string,leagueId:string,status:string,hs:string|null,as:string|null,date=dateNow(),round=''):Match {return {id,home:clubs.find(c=>c[0]===home)?.[1]||home,away:clubs.find(c=>c[0]===away)?.[1]||away,homeId:home,awayId:away,leagueId,league:demoLeagues.find(l=>l.id===leagueId)?.name||'',country:demoLeagues.find(l=>l.id===leagueId)?.country||'',homeScore:hs,awayScore:as,date,kickoff:date+'T19:00:00Z',status,progress:status==='2H'?"67′":'',round,group:'',venue:'האצטדיון הביתי',season:'2026/27'};}
export const demoGames=()=>[game('d1','haifa','הפועל באר שבע','israel','2H','1','1'),game('d2','telaviv','מ.ס. אשדוד','israel','FT','2','0'),game('d3','בית״ר ירושלים','מכבי נתניה','israel','FT','0','0'),game('d4','barcelona','madrid','champions','2H','2','1'),game('d5','arsenal','liverpool','england','NS',null,null),game('d6','bayern','inter','champions','NS',null,null),game('d7','barcelona','dortmund','champions','FT','3','1',dateNow(),'שמינית גמר')];
export const demoAlerts:AlertItem[]=[{id:'demo-goal',matchId:'d4',title:'שער לברצלונה',body:'לאמין ימאל כובש! ברצלונה 2 : 1 ריאל מדריד',at:new Date().toISOString(),read:false},{id:'demo-start',matchId:'d1',title:'המשחק בעיצומו',body:'מכבי חיפה מול הפועל באר שבע',at:new Date().toISOString(),read:false}];
const basketLeagues:League[]=[{id:'basket-nba',sport:'Basketball',name:'ליגת הכדורסל',country:'World',season:'2026-2027'},{id:'basket-euro',sport:'Basketball',name:'ליגת אירופה בכדורסל',country:'Europe',season:'2026-2027'}];
const basketGames=():Match[]=>[['b1','צפון סיטי','דרום אתלטיק','basket-nba','Q3','78','75'],['b2','חוף ארנה','עמק יונייטד','basket-nba','FT','101','96'],['b3','פסגה ספורט','נמל סיטי','basket-euro','NS',null,null]].map(([id,home,away,leagueId,status,homeScore,awayScore])=>({id:id!,home:home!,away:away!,leagueId:leagueId!,league:basketLeagues.find(l=>l.id===leagueId)?.name||'',sport:'Basketball',country:'World',homeId:'demo-'+home,awayId:'demo-'+away,homeScore:homeScore||null,awayScore:awayScore||null,date:dateNow(),kickoff:dateNow()+'T19:00:00Z',status:status!,progress:'',round:'',group:'',venue:'',season:'2026-2027'}));
export function demoData(p:URLSearchParams):unknown {
 if(p.get('sport')==='Basketball'){
  const view=p.get('view'),matches=basketGames();
  if(view==='day')return {matches:matches.map(m=>({...m,date:p.get('date')||m.date,kickoff:(p.get('date')||m.date)+'T19:00:00Z'})),limited:false,liveState:'unconfigured',fetchedAt:new Date().toISOString()};
  if(view==='leagues')return {leagues:basketLeagues,limited:false};
  if(view==='event')return {match:matches.find(m=>m.id===p.get('id'))||matches[0],lineup:[],timeline:[],stats:[{name:'Rebounds',home:'32',away:'28'},{name:'Assists',home:'18',away:'15'}],limited:false,unavailable:[]};
  if(view==='league')return {league:basketLeagues.find(l=>l.id===p.get('id'))||basketLeagues[0],seasons:['2026-2027'],limited:false};
  if(view==='season')return {rows:[],matches,limited:false,tableError:false,matchesError:false,tableSeason:'2026-2027'};
 }
 const view=p.get('view'),id=p.get('id'),games=demoGames();
 if(view==='legionnaire-search')return {players:legionnaires.filter(x=>`${x.name} ${x.english}`.toLowerCase().includes((p.get('q')||'').toLowerCase()))};
 if(view==='legionnaire'){const player=legionnaires.find(x=>x.id===id)||legionnaires[0];const index=legionnaires.indexOf(player);const match={...games[index%games.length],id:'leg-demo-'+player.id,home:hebrewTeam(player.team),homeId:player.teamId,homeBadge:player.badge};return {player,match,lineup:index%3===0?'starter':index%3===1?'bench':'unknown',eligible:true,partial:false,checkedAt:new Date().toISOString()};}
 if(view==='cards')return {cards:{homeYellow:2,awayYellow:3,homeRed:0,awayRed:id==='d4'?1:0}};
 if(view==='day')return {matches:games.map(m=>({...m,date:p.get('date')||m.date,kickoff:(p.get('date')||m.date)+'T19:00:00Z'})),limited:false,liveState:'unconfigured',fetchedAt:new Date().toISOString()};
 if(view==='leagues')return {leagues:demoLeagues,limited:false};
 if(view==='search')return {teams:clubs.filter(c=>c[1].includes(p.get('q')||'')||c[0].includes(p.get('q')||'')).map(([id,name])=>({id,name,country:'',league:''}))};
 if(view==='league')return {league:demoLeagues.find(l=>l.id===id)||demoLeagues[0],seasons:['2026/27','2025/26'],limited:false};
 if(view==='season')return {rows:(id==='israel'?[clubs[3],clubs[2],...clubs.slice(9)]:id==='england'?[clubs[4],clubs[5]]:id==='spain'?clubs.slice(0,2):clubs.slice(0,9)).map(([id,name],i)=>({id,name,rank:i+1,played:'21',wins:String(17-i),draws:'3',losses:String(i+1),difference:'+'+(22-i*3),points:String(54-i*5),form:'WWDWW'})),matches:id==='champions'?[...games.filter(m=>m.leagueId===id),game('semi1','barcelona','bayern','champions','NS',null,null,dateNow(),'חצי גמר'),game('semi2','madrid','arsenal','champions','NS',null,null,dateNow(),'חצי גמר'),game('final','טרם נקבע','טרם נקבע','champions','NS',null,null,dateNow(),'גמר')]:games.filter(m=>m.leagueId===id),limited:false,tableError:false,matchesError:false,tableSeason:p.get('season')};
 if(view==='team')return {name:clubs.find(c=>c[0]===id)?.[1]||id,country:id==='haifa'||id==='telaviv'?'Israel':'Spain',venue:id==='haifa'?'סמי עופר':'האצטדיון הביתי',leagueId:id==='haifa'||id==='telaviv'?'israel':'spain',league:id==='haifa'||id==='telaviv'?'ליגת העל':'לה ליגה',matches:[game('next-'+id,id||'barcelona','telaviv','israel','NS',null,null),...Array.from({length:5},(_,i)=>game('history-'+id+'-'+i,id||'barcelona',clubs[(i+1)%clubs.length][0],'champions','FT',String(i%3+1),String(i%2),'2026-09-'+String(20-i*3).padStart(2,'0')))],limited:false,partial:false};
 if(view==='event') {const match=id?.startsWith('leg-demo-')?(demoData(new URLSearchParams({view:'legionnaire',id:id.slice(9)})) as {match:Match}).match:games.find(m=>m.id===id)||game(id||'d4','barcelona','madrid','champions','FT','2','1');return {match,lineup:match.id==='d4'?[true,false].flatMap(home=>(home?['טר שטגן','קונדה','קובארסי','אראוחו','באלדה','פדרי','דה יונג','גאבי','לאמין ימאל','לבנדובסקי','ראפיניה']:['קורטואה','קרבחאל','רודיגר','מיליטאו','מנדי','ואלוורדה','טשואמני','בלינגהאם','רודריגו','אמבפה','ויניסיוס']).map((name,i)=>({id:home+'-'+i,name,home,substitute:false,position:i===0?'Goalkeeper':i<5?'Defender':i<8?'Midfielder':'Forward',number:String([1,23,5,4,3,8,21,6,19,9,11][i])}))):[],stats:[['Ball Possession','58%','42%'],['Total Shots','14','9'],['Shots on Goal','7','4'],['Corner Kicks','6','3'],['Fouls','10','12'],['expected_goals','2.1','0.8']].map(([name,home,away])=>({name,home,away})),timeline:match.id==='d4'?[['67','Goal','Normal Goal','לאמין ימאל',true],['61','Card','Yellow Card','טשואמני',false],['54','subst','חילוף','מודריץ׳ ← בלינגהאם',false],['32','Goal','Normal Goal','ויניסיוס',false],['28','Card','Yellow Card','גאבי',true],['15','Goal','Normal Goal','לבנדובסקי',true]].map(([minute,kind,detail,player,home],i)=>({id:String(i),minute,kind,detail,player,home,team:home?match.home:match.away})):[],limited:false,unavailable:[]};}
 return {};
}
