import {basketballTeams,footballTeams} from "./team-names";

const entries: [string,string][] = [
["Scotland", "סקוטלנד"],
["Wales", "ויילס"],
["Northern Ireland", "צפון אירלנד"],
["Republic of Ireland", "אירלנד"],
["Ireland Republic", "אירלנד"],
["Czech Republic", "צ׳כיה"],
["Turkey", "טורקיה"],
["Türkiye", "טורקיה"],
["Korea Republic", "דרום קוריאה"],
["Korea DPR", "צפון קוריאה"],
["Korea South", "דרום קוריאה"],
["Korea North", "צפון קוריאה"],
["United States", "ארצות הברית"],
["United States of America", "ארצות הברית"],
["USA", "ארצות הברית"],
["Iran", "איראן"],
["IR Iran", "איראן"],
["Russia", "רוסיה"],
["Vietnam", "וייטנאם"],
["Chinese Taipei", "טאיוואן"],
["Hong Kong", "הונג קונג"],
["Macau", "מקאו"],
["Macao", "מקאו"],
["Palestine", "פלסטין"],
["Cape Verde", "כף ורדה"],
["Cabo Verde", "כף ורדה"],
["Ivory Coast", "חוף השנהב"],
["Cote d'Ivoire", "חוף השנהב"],
["Côte d’Ivoire", "חוף השנהב"],
["DR Congo", "הרפובליקה הדמוקרטית של קונגו"],
["Congo DR", "הרפובליקה הדמוקרטית של קונגו"],
["Congo", "קונגו"],
["Democratic Republic of the Congo", "הרפובליקה הדמוקרטית של קונגו"],
["Swaziland", "אסוואטיני"],
["Macedonia", "צפון מקדוניה"],
["FYR Macedonia", "צפון מקדוניה"],
["Bosnia-Herzegovina", "בוסניה והרצגובינה"],
["Bosnia and Herzegovina", "בוסניה והרצגובינה"],
["Curacao", "קוראסאו"],
["Saint Kitts and Nevis", "סנט קיטס ונוויס"],
["St Kitts and Nevis", "סנט קיטס ונוויס"],
["Saint Vincent and the Grenadines", "סנט וינסנט והגרנדינים"],
["St Vincent and Grenadines", "סנט וינסנט והגרנדינים"],
["Tahiti", "טהיטי"],
["New Caledonia", "קלדוניה החדשה"],
["Timor Leste", "מזרח טימור"],
["Man Utd", "מנצ׳סטר יונייטד"],
["Man United", "מנצ׳סטר יונייטד"],
["Man City", "מנצ׳סטר סיטי"],
["Brighton and Hove Albion", "ברייטון"],
["AFC Bournemouth", "בורנמות׳"],
["West Brom", "ווסט ברומיץ׳"],
["West Bromwich Albion", "ווסט ברומיץ׳"],
["Sheffield United", "שפילד יונייטד"],
["Sheffield Wednesday", "שפילד ונסדיי"],
["Coventry City", "קובנטרי"],
["Birmingham City", "ברמינגהאם"],
["Middlesbrough", "מידלסברו"],
["Watford", "ווטפורד"],
["Norwich City", "נוריץ׳"],
["Stoke City", "סטוק סיטי"],
["Blackburn Rovers", "בלקבורן"],
["Derby County", "דרבי קאונטי"],
["Swansea City", "סוונסי"],
["Cardiff City", "קארדיף"],
["Queens Park Rangers", "קווינס פארק ריינג׳רס"],
["Deportivo Alaves", "אלאבס"],
["Deportivo La Coruna", "דפורטיבו לה קורוניה"],
["Real Valladolid", "ויאדוליד"],
["Las Palmas", "לאס פלמאס"],
["Real Oviedo", "ריאל אוביידו"],
["Racing Santander", "ראסינג סנטנדר"],
["Sporting Gijon", "ספורטינג חיחון"],
["Malaga", "מלאגה"],
["Granada", "גרנאדה"],
["Almeria", "אלמריה"],
["Bayern Munchen", "באיירן מינכן"],
["FC Bayern München", "באיירן מינכן"],
["Borussia Mönchengladbach", "בורוסיה מנשנגלדבאך"],
["Borussia M'gladbach", "בורוסיה מנשנגלדבאך"],
["FSV Mainz 05", "מיינץ"],
["1. FC Köln", "קלן"],
["1. FC Heidenheim", "היידנהיים"],
["Schalke 04", "שאלקה"],
["Hertha BSC", "הרטה ברלין"],
["Hannover 96", "האנובר"],
["Fortuna Dusseldorf", "פורטונה דיסלדורף"],
["St Pauli", "סנט פאולי"],
["Darmstadt 98", "דרמשטאדט"],
["Sampdoria", "סמפדוריה"],
["Empoli", "אמפולי"],
["Monza", "מונצה"],
["Spezia", "ספציה"],
["Palermo", "פאלרמו"],
["Venezia", "ונציה"],
["Salernitana", "סלרניטנה"],
["PSG", "פריז סן ז׳רמן"],
["Paris Saint Germain", "פריז סן ז׳רמן"],
["Olympique Marseille", "מארסיי"],
["Olympique de Marseille", "מארסיי"],
["Olympique Lyonnais", "ליון"],
["Stade Rennais", "ראן"],
["Stade Brestois 29", "ברסט"],
["Saint Etienne", "סנט אטיין"],
["Reims", "ריימס"],
["Montpellier", "מונפלייה"],
["Angers", "אנז׳ה"],
["PSV", "פ.ס.וו. איינדהובן"],
["AZ Alkmaar", "אלקמאר"],
["Utrecht", "אוטרכט"],
["Hearts", "הארטס"],
["Heart of Midlothian", "הארטס"],
["Aberdeen", "אברדין"],
["Hibernian", "היברניאן"],
["Braga", "בראגה"],
["Vitoria Guimaraes", "ויטוריה גימראייש"],
["FC Copenhagen", "קופנהגן"],
["FC København", "קופנהגן"],
["Midtjylland", "מיטיילן"],
["Brondby", "ברונדבי"],
["Bodo Glimt", "בודו גלימט"],
["Bodø/Glimt", "בודו גלימט"],
["Molde", "מולדה"],
["Rosenborg", "רוזנבורג"],
["Malmo FF", "מאלמו"],
["Young Boys", "יאנג בויז"],
["Basel", "באזל"],
["Zurich", "ציריך"],
["Servette", "סרבט"],
["Sturm Graz", "שטורם גראץ"],
["Rapid Vienna", "ראפיד וינה"],
["Austria Vienna", "אוסטריה וינה"],
["Slavia Prague", "סלביה פראג"],
["Sparta Prague", "ספרטה פראג"],
["Viktoria Plzen", "ויקטוריה פלזן"],
["Slovan Bratislava", "סלובן ברטיסלבה"],
["Legia Warsaw", "לגיה ורשה"],
["Lech Poznan", "לך פוזנן"],
["Rakow Czestochowa", "ראקוב צ׳נסטוחובה"],
["Union Saint-Gilloise", "אוניון סן ז׳ילואז"],
["Genk", "גנק"],
["Gent", "גנט"],
["Standard Liege", "סטנדרד ליאז׳"],
["Antwerp", "אנטוורפן"],
["AEK Athens", "א.א.ק. אתונה"],
["PAOK", "פאוק סלוניקי"],
["Aris Thessaloniki", "אריס סלוניקי"],
["APOEL", "אפואל ניקוסיה"],
["AEK Larnaca", "א.א.ק. לרנקה"],
["Pafos", "פאפוס"],
["Qarabag", "קרבאך"],
["Qarabağ FK", "קרבאך"],
["FCSB", "סטיאווה בוקרשט"],
["Steaua Bucharest", "סטיאווה בוקרשט"],
["Trabzonspor", "טרבזונספור"],
["Istanbul Basaksehir", "איסטנבול בשאקשהיר"],
["Inter Miami", "אינטר מיאמי"],
["LA Galaxy", "לוס אנג׳לס גלקסי"],
["Los Angeles FC", "לוס אנג׳לס"],
["New York City FC", "ניו יורק סיטי"],
["New York Red Bulls", "ניו יורק רד בולס"],
["Atlanta United", "אטלנטה יונייטד"],
["Seattle Sounders", "סיאטל סאונדרס"],
["Portland Timbers", "פורטלנד טימברס"],
["Columbus Crew", "קולומבוס קרו"],
["Toronto FC", "טורונטו"],
["Boca Juniors", "בוקה ג׳וניורס"],
["River Plate", "ריבר פלייט"],
["Flamengo", "פלמנגו"],
["Palmeiras", "פלמייראס"],
["Santos", "סנטוס"],
["Sao Paulo", "סאו פאולו"],
["Corinthians", "קורינתיאנס"],
["Fluminense", "פלומיננזה"],
["Botafogo", "בוטפוגו"],
["Gremio", "גרמיו"],
["Internacional", "אינטרנסיונל"],
["Al Hilal", "אל הילאל"],
["Al Nassr", "אל נאסר"],
["Al Ittihad", "אל איתיחאד"],
["Al Ahli", "אל אהלי"],
["Al Ahly", "אל אהלי קהיר"],
["Zamalek", "זמאלק"],
["Boston Celtics", "בוסטון סלטיקס"],
["Brooklyn Nets", "ברוקלין נטס"],
["New York Knicks", "ניו יורק ניקס"],
["Philadelphia 76ers", "פילדלפיה סיקסרס"],
["Toronto Raptors", "טורונטו ראפטורס"],
["Chicago Bulls", "שיקגו בולס"],
["Cleveland Cavaliers", "קליבלנד קאבלירס"],
["Detroit Pistons", "דטרויט פיסטונס"],
["Indiana Pacers", "אינדיאנה פייסרס"],
["Milwaukee Bucks", "מילווקי באקס"],
["Atlanta Hawks", "אטלנטה הוקס"],
["Charlotte Hornets", "שארלוט הורנטס"],
["Miami Heat", "מיאמי היט"],
["Orlando Magic", "אורלנדו מג׳יק"],
["Washington Wizards", "וושינגטון וויזארדס"],
["Denver Nuggets", "דנבר נאגטס"],
["Minnesota Timberwolves", "מינסוטה טימברוולבס"],
["Oklahoma City Thunder", "אוקלהומה סיטי ת׳אנדר"],
["Portland Trail Blazers", "פורטלנד טרייל בלייזרס"],
["Utah Jazz", "יוטה ג׳אז"],
["Golden State Warriors", "גולדן סטייט ווריורס"],
["Los Angeles Lakers", "לוס אנג׳לס לייקרס"],
["Los Angeles Clippers", "לוס אנג׳לס קליפרס"],
["LA Clippers", "לוס אנג׳לס קליפרס"],
["Phoenix Suns", "פיניקס סאנס"],
["Sacramento Kings", "סקרמנטו קינגס"],
["Dallas Mavericks", "דאלאס מאבריקס"],
["Houston Rockets", "יוסטון רוקטס"],
["Memphis Grizzlies", "ממפיס גריזליס"],
["New Orleans Pelicans", "ניו אורלינס פליקנס"],
["San Antonio Spurs", "סן אנטוניו ספרס"],
["Fenerbahce Beko", "פנרבחצ׳ה"],
["Anadolu Efes", "אנאדולו אפס"],
["Baskonia", "באסקוניה"],
["Zalgiris Kaunas", "ז׳לגיריס קובנה"],
["Zalgiris", "ז׳לגיריס קובנה"],
["Virtus Bologna", "וירטוס בולוניה"],
["Olimpia Milano", "אולימפיה מילאנו"],
["ASVEL Lyon Villeurbanne", "וילרבאן"],
["ASVEL", "וילרבאן"],
["Alba Berlin", "אלבה ברלין"],
["Valencia Basket", "ולנסיה"],
["Hapoel Holon", "הפועל חולון"],
["Bnei Herzliya", "בני הרצליה"],
["Ironi Ness Ziona", "עירוני נס ציונה"],
["Hapoel Gilboa Galil", "הפועל גלבוע גליל"],
["Hapoel Galil Elyon", "הפועל גליל עליון"],
["Hapoel Eilat", "הפועל אילת"],
["Maccabi Rishon LeZion", "מכבי ראשון לציון"],
["Elitzur Netanya", "אליצור נתניה"],
["Maccabi Ironi Ramat Gan", "מכבי עירוני רמת גן"],
['Sumgayit FK','סומגאיט'],['Kortrijk','קורטרייק'],
['Crvena Zvezda','הכוכב האדום בלגרד'],['Twente','טוונטה'],['NEC Nijmegen','ניימכן'],['Ludogorets Razgrad','לודוגורץ'],['Machida Zelvia','מצ׳ידה זלביה'],['Charlotte FC','שארלוט'],['New England Revolution','ניו אינגלנד רבולושן'],['Kairat Almaty','קאיראט אלמטי'],['DC United','די.סי. יונייטד'],['Yokohama F Marinos','יוקוהמה מרינוס'],['Ferencvaros','פרנצווארוש'],['Ferencváros','פרנצווארוש'],['Ferencvárosi TC','פרנצווארוש'],['Partizan','פרטיזן בלגרד'],['Partizan Belgrade','פרטיזן בלגרד'],['Antalyaspor','אנטליאספור'],['Chengdu Rongcheng','צ׳נגדו רונגצ׳נג'],['Dinamo Minsk','דינמו מינסק'],['Volos','וולוס'],['Omonia Nicosia','אומוניה ניקוסיה'],['Heracles Almelo','הראקלס אלמלו'],['Sumqayit','סומגאיט'],
['Hapoel Ironi Kiryat Shmona','עירוני קריית שמונה'],['Hapoel Tel-Aviv','הפועל תל אביב'],["Hapoel Be'er Sheva",'הפועל באר שבע'],['Maccabi Tel Aviv','מכבי תל אביב'],['Maccabi Haifa','מכבי חיפה'],['Hapoel Beer Sheva','הפועל באר שבע'],['Hapoel Be’er Sheva','הפועל באר שבע'],['Hapoel Beersheba','הפועל באר שבע'],['Beitar Jerusalem','בית״ר ירושלים'],['Maccabi Netanya','מכבי נתניה'],['Hapoel Tel Aviv','הפועל תל אביב'],['Hapoel Haifa','הפועל חיפה'],['Hapoel Jerusalem','הפועל ירושלים'],['Hapoel Petah Tikva','הפועל פתח תקווה'],['Maccabi Petah Tikva','מכבי פתח תקווה'],['Bnei Sakhnin','בני סכנין'],['Ironi Kiryat Shmona','עירוני קריית שמונה'],['Hapoel Kiryat Shmona','עירוני קריית שמונה'],['Ironi Tiberias','עירוני טבריה'],['Ashdod','מ.ס. אשדוד'],['FC Ashdod','מ.ס. אשדוד'],['M.S. Ashdod','מ.ס. אשדוד'],['Maccabi Bnei Raina','מכבי בני ריינה'],['Maccabi Bnei Reineh','מכבי בני ריינה'],['Hapoel Hadera','הפועל חדרה'],['Hapoel Kfar Saba','הפועל כפר סבא'],['Hapoel Ramat Gan','הפועל רמת גן'],['Hapoel Rishon LeZion','הפועל ראשון לציון'],['Hapoel Rishon Lezion','הפועל ראשון לציון'],['Bnei Yehuda','בני יהודה'],['Bnei Yehuda Tel Aviv','בני יהודה'],['Hapoel Ramat HaSharon','הפועל רמת השרון'],['Hapoel Afula','הפועל עפולה'],['Hapoel Acre','הפועל עכו'],['Hapoel Akko','הפועל עכו'],['Hapoel Nof HaGalil','הפועל נוף הגליל'],['Hapoel Nof Hagalil','הפועל נוף הגליל'],['Hapoel Umm al-Fahm','הפועל אום אל־פחם'],['Hapoel Kfar Shalem','הפועל כפר שלם'],['Hapoel Ra’anana','הפועל רעננה'],['Hapoel Raanana','הפועל רעננה'],['Maccabi Herzliya','מכבי הרצליה'],['Hapoel Herzliya','הפועל הרצליה'],['Kafr Qasim','מ.ס. כפר קאסם'],['M.S. Kafr Qasim','מ.ס. כפר קאסם'],['Maccabi Jaffa','מכבי יפו'],['Maccabi Kabilio Jaffa','מכבי יפו'],['Hapoel Kfar Qasim','הפועל כפר קאסם'],['Hapoel Kfar Saba 1928','הפועל כפר סבא'],['Hapoel Natzrat Illit','הפועל נוף הגליל'],
['Barcelona','ברצלונה'],['FC Barcelona','ברצלונה'],['Real Madrid','ריאל מדריד'],['Atletico Madrid','אתלטיקו מדריד'],['Atlético Madrid','אתלטיקו מדריד'],['Athletic Bilbao','אתלטיק בילבאו'],['Athletic Club','אתלטיק בילבאו'],['Real Sociedad','ריאל סוסיאדד'],['Real Betis','ריאל בטיס'],['Sevilla','סביליה'],['Valencia','ולנסיה'],['Villarreal','ויאריאל'],['Girona','ג׳ירונה'],['Getafe','חטאפה'],['Osasuna','אוססונה'],['Celta Vigo','סלטה ויגו'],['Espanyol','אספניול'],['Mallorca','מאיורקה'],['Rayo Vallecano','ראיו ואיקאנו'],['Alaves','אלאבס'],['Levante','לבאנטה'],['Elche','אלצ׳ה'],
['Arsenal','ארסנל'],['Liverpool','ליברפול'],['Manchester City','מנצ׳סטר סיטי'],['Manchester United','מנצ׳סטר יונייטד'],['Chelsea','צ׳לסי'],['Tottenham','טוטנהאם'],['Tottenham Hotspur','טוטנהאם'],['Newcastle','ניוקאסל'],['Newcastle United','ניוקאסל'],['Aston Villa','אסטון וילה'],['Brighton','ברייטון'],['Brighton & Hove Albion','ברייטון'],['West Ham','ווסטהאם'],['West Ham United','ווסטהאם'],['Everton','אברטון'],['Fulham','פולהאם'],['Crystal Palace','קריסטל פאלאס'],['Brentford','ברנטפורד'],['Bournemouth','בורנמות׳'],['Nottingham Forest','נוטינגהאם פורסט'],['Wolves','וולבס'],['Wolverhampton Wanderers','וולבס'],['Leeds United','לידס יונייטד'],['Burnley','ברנלי'],['Sunderland','סנדרלנד'],['Leicester City','לסטר סיטי'],['Southampton','סאות׳המפטון'],['Ipswich Town','איפסוויץ׳'],
['Bayern Munich','באיירן מינכן'],['Bayern München','באיירן מינכן'],['Borussia Dortmund','בורוסיה דורטמונד'],['Bayer Leverkusen','באייר לברקוזן'],['RB Leipzig','ר.ב. לייפציג'],['Eintracht Frankfurt','איינטרכט פרנקפורט'],['Borussia Monchengladbach','בורוסיה מנשנגלדבאך'],['VfB Stuttgart','שטוטגרט'],['Stuttgart','שטוטגרט'],['Freiburg','פרייבורג'],['Wolfsburg','וולפסבורג'],['Werder Bremen','ורדר ברמן'],['Mainz','מיינץ'],['Augsburg','אוגסבורג'],['Hoffenheim','הופנהיים'],['Union Berlin','אוניון ברלין'],['Hamburger SV','המבורג'],['Heidenheim','היידנהיים'],['FC Koln','קלן'],
['Inter Milan','אינטר'],['Inter','אינטר'],['Internazionale','אינטר'],['AC Milan','מילאן'],['Juventus','יובנטוס'],['Napoli','נאפולי'],['Roma','רומא'],['AS Roma','רומא'],['Lazio','לאציו'],['Atalanta','אטאלנטה'],['Fiorentina','פיורנטינה'],['Bologna','בולוניה'],['Torino','טורינו'],['Udinese','אודינזה'],['Genoa','גנואה'],['Parma','פארמה'],['Cagliari','קליארי'],['Lecce','לצ׳ה'],['Como','קומו'],['Sassuolo','ססואולו'],['Pisa','פיזה'],['Cremonese','קרמונזה'],['Hellas Verona','ורונה'],
['Paris Saint-Germain','פריז סן ז׳רמן'],['Paris SG','פריז סן ז׳רמן'],['Marseille','מארסיי'],['Lyon','ליון'],['Monaco','מונאקו'],['Lille','ליל'],['Nice','ניס'],['Rennes','ראן'],['Lens','לאנס'],['Strasbourg','שטרסבורג'],['Nantes','נאנט'],['Toulouse','טולוז'],['Brest','ברסט'],['Auxerre','אוקזר'],['Lorient','לוריאן'],['Metz','מץ'],['Le Havre','לה האבר'],['Paris FC','פריז'],
['Ajax','אייאקס'],['PSV Eindhoven','פ.ס.וו. איינדהובן'],['Feyenoord','פיינורד'],['Benfica','בנפיקה'],['Porto','פורטו'],['Sporting CP','ספורטינג ליסבון'],['Sporting Lisbon','ספורטינג ליסבון'],['Celtic','סלטיק'],['Rangers','ריינג׳רס'],['Galatasaray','גלאטסראיי'],['Fenerbahce','פנרבחצ׳ה'],['Besiktas','בשיקטאש'],['Olympiacos','אולימפיאקוס'],['Panathinaikos','פנאתינייקוס'],['Red Bull Salzburg','רד בול זלצבורג'],['Club Brugge','קלאב ברוז׳'],['Anderlecht','אנדרלכט'],['Shakhtar Donetsk','שחטאר דונייצק'],['Dynamo Kyiv','דינמו קייב'],['Red Star Belgrade','הכוכב האדום בלגרד'],['Dinamo Zagreb','דינמו זאגרב'],
['Israel','ישראל'],['England','אנגליה'],['Spain','ספרד'],['France','צרפת'],['Germany','גרמניה'],['Italy','איטליה'],['Portugal','פורטוגל'],['Netherlands','הולנד'],['Brazil','ברזיל'],['Argentina','ארגנטינה'],['Belgium','בלגיה'],['Croatia','קרואטיה'],['Japan','יפן'],['South Korea','דרום קוריאה'],['Australia','אוסטרליה'],['USA','ארצות הברית']
];
// Normalize provider spelling without fuzzy matching different clubs.
const canonical=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[’'`./()-]/g,' ').replace(/\s+/g,' ').trim();
const allTeams=[...footballTeams,...basketballTeams,...entries];
const labels=new Map(allTeams.map(([en,he])=>[canonical(en),he]));
// ISO region names cover national teams worldwide; provider aliases above win.
const regions="AD AE AF AG AI AL AM AO AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW".split(" ");
const englishRegions=new Intl.DisplayNames(['en'],{type:'region'});
const hebrewRegions=new Intl.DisplayNames(['he'],{type:'region'});
for(const code of regions){const en=englishRegions.of(code),he=hebrewRegions.of(code);if(en&&he&&!labels.has(canonical(en)))labels.set(canonical(en),he);}
export function hebrewTeam(name:string):string {
 const key=canonical(name),direct=labels.get(key);
 if(direct)return direct;
 // Recognize age/women suffixes but never collapse those teams into the senior team.
 const qualified=name.match(/^(.*?)\s+(?:\(?)(U[ -]?(\d{2})|Under[ -]?(\d{2})|Women(?:'s)?|Ladies|W)(?:\)?)$/i);
 if(qualified){const base=hebrewTeam(qualified[1]);if(base!==qualified[1]||/[\u0590-\u05ff]/.test(base)){const age=qualified[3]||qualified[4];return `${base} · ${age?`עד גיל ${age}`:'נשים'}`;}}
 let clubKey=key;
 for(let i=0;i<3;i++){
  const next=clubKey.replace(clubPrefix,'').replace(clubSuffix,'');
  if(next===clubKey||!next)break;
  clubKey=next;
  const hit=labels.get(clubKey);
  if(hit)return hit;
 }
 return name;
}
const clubPrefix=/^(?:fc|afc|sc|cf|ac|as|rc|ogc|vfl|vfb|sv|ss|ssc|us|uc|tsg|bc|kk|bk|cb|pbc|ks|nk|hnk|fk|a s|b c|k k) /;
const clubSuffix=/ (?:fc|afc|sc|cf|fk|sk|bk|bc|b c|kk|bb|cab|basket|basketball|basketbol|baloncesto|basquet|pallacanestro|b b c|bbc)$/;
export const searchTeamQuery=(query:string)=>allTeams.find(([,he])=>he===query)?.[0]||regions.map(code=>englishRegions.of(code)).find(en=>en&&hebrewTeam(en)===query)||query;
const foldHebrew=(s:string)=>s.replace(/[׳״'"`.\-־]/g,'').replace(/\s+/g,' ').trim();
// Hebrew queries are mapped back to provider spellings so the English-only API can search them.
export function searchCandidates(query:string,limit=4):string[]{
 const q=foldHebrew(query);
 if(!/[\u0590-\u05ff]/.test(q))return [query];
 const scored=new Map<string,{en:string;score:number;index:number}>();
 for(const [index,[en,he]] of [...entries,...footballTeams,...basketballTeams].entries()){
  const label=foldHebrew(he);
  const score=label===q?0:label.startsWith(q)?1:label.split(' ').some(w=>w.startsWith(q))?2:label.includes(q)?3:-1;
  if(score<0)continue;
  if(!scored.has(he))scored.set(he,{en,score,index});
 }
 return [...scored.values()].sort((a,b)=>a.score-b.score||a.index-b.index).slice(0,limit).map(x=>x.en);
}
export function displayName(name:string){return name.split(/\s+[–—]\s+/).map(hebrewTeam).join(' – ');}

export function displayResult(text:string){const result=text.match(/^(.*?)\s+(\d+|–)\s*:\s*(\d+|–)\s+(.+)$/);return result?`${hebrewTeam(result[1])} ${result[2]} : ${result[3]} ${hebrewTeam(result[4])}`:displayName(text);}

export function splitTeamAgeLabel(value:string):{primary:string;age?:string}{
 const label=hebrewTeam(value);
 const match=label.match(/^(.*?)\s*(?:[·•]\s*)?(עד גיל\s*\d{1,2})$/);
 return match&&match[1].replace(/[·•\s]+$/g,"")
  ? {primary:match[1].replace(/[·•\s]+$/g,""),age:match[2]}
  : {primary:label};
}
