"use client";
import { ArrowLeft, ChevronLeft, Radio, Star, Trophy, CalendarDays, ShieldCheck } from 'lucide-react';
import type { Match, League, Favorite } from '@/lib/football/types';
import { isLive, isFinished, liveMinute, leagueName, countryName } from '@/lib/football/types';
import { displayName } from '@/lib/football/names';
import { clock } from '@/lib/football/client';
import { Emblem, FavoriteButton } from './ui';
type Props={matches:Match[];leagues:League[];favorites:Favorite[];openMatch:(m:Match)=>void;openLeague:(l:League)=>void;openFavorite:(f:Favorite)=>void;has:(kind:Favorite['kind'],id:string)=>boolean;toggle:(f:Favorite)=>void;showLeagues:()=>void;showFavorites:()=>void;showLegionnaires:()=>void;showLive:()=>void;demo:boolean};
export function DesktopHero({showLive,showFavorites}:{showLive:()=>void;showFavorites:()=>void}){return <section className="desktop-hero"><img src="/brand/desktop-football.png" alt="שחקני כדורגל בדיוניים באצטדיון"/><div className="desktop-hero-copy"><span className="hero-overline">KICKOFF · הבית של המשחק</span><h2>כל המשחק.<br/>בלי ההפרעות.</h2><p>תוצאות, רגעים ומועדפים. הכדורגל שלך, במקום אחד.</p><div><button onClick={showLive}>למשחקים החיים <ArrowLeft size={16}/></button><button className="hero-secondary" onClick={showFavorites}><Star size={15}/>המעקב שלי</button></div></div><small className="hero-art-credit">יצירה מקורית · שחקנים בדיוניים</small></section>}
export function DesktopLeagueRail(p:Props){const featured=p.matches.find(m=>isLive(m.status))||p.matches[0];const preferred=['ליגת העל','ליגת האלופות','פרמייר ליג','לה ליגה','סרייה א׳','בונדסליגה','ליג 1'];const leagues=[...p.leagues].sort((a,b)=>{const x=preferred.indexOf(leagueName(a.name)),y=preferred.indexOf(leagueName(b.name));return (x<0?99:x)-(y<0?99:y)}).slice(0,9);return <><section className="desk-panel featured-match"><div className="desk-section-heading"><span>על המגרש</span><Radio size={16}/></div>{featured?<><div className="featured-league">{leagueName(featured.league)}<span className={isLive(featured.status)?'live-label':''}>{isLive(featured.status)?liveMinute(featured):isFinished(featured.status)?'הסתיים':clock(featured.kickoff)}</span></div><div className="featured-score"><div><Emblem name={featured.home} id={featured.homeId} src={featured.homeBadge}/><strong>{displayName(featured.home)}</strong></div><b dir="ltr">{featured.homeScore??'–'}<span>:</span>{featured.awayScore??'–'}</b><div><Emblem name={featured.away} id={featured.awayId} src={featured.awayBadge}/><strong>{displayName(featured.away)}</strong></div></div><div className="featured-actions"><button className="desk-primary" onClick={()=>p.openMatch(featured)}>מרכז המשחק<ChevronLeft size={15}/></button><FavoriteButton item={{kind:'match',id:featured.id,name:`${featured.home} – ${featured.away}`}} saved={p.has('match',featured.id)} toggle={p.toggle}/></div></>:<div className="rail-empty"><CalendarDays size={28}/><p>המשחקים יופיעו כאן כשהנתונים יהיו זמינים.</p></div>}</section><section className="desk-panel league-rail"><div className="desk-section-heading"><span>הליגות והתחרויות</span><Trophy size={16}/></div>{leagues.map(l=><button className="rail-league" key={l.id} onClick={()=>p.openLeague(l)}><Emblem name={leagueName(l.name)} id={l.id} kind="league" src={l.badge} small/><span>{leagueName(l.name)}<small>{countryName(l.country)}</small></span><ChevronLeft size={14}/></button>)}<button className="rail-more" onClick={p.showLeagues}>לכל התחרויות<ArrowLeft size={14}/></button></section><div className="rail-promise"><ShieldCheck size={19}/><span>חינם למשתמשים.<br/><strong>בלי פרסומות. רק כדורגל.</strong></span></div></>}
export function DesktopContentRail(p:Props){const upcoming=p.matches.filter(m=>!isLive(m.status)&&!isFinished(m.status)).slice(0,4);return <aside className="desktop-content-rail"><section className="desk-panel editorial-panel"><div className="desk-section-heading"><span>מעבר לתוצאה</span><span className="editorial-dot"/></div><button className="editorial-image" onClick={p.showLegionnaires}><img src="/brand/legionnaires-purple.webp" alt="איור ספורט עם שחקנים בדיוניים"/><span>הישראלים בחו״ל<strong>הסיפור ממשיך<br/>גם מעבר לים.</strong><span className="editorial-link">למרכז הליגיונרים <ArrowLeft size={15}/></span></span></button><p className="editorial-caption">הקבוצות, המשחקים וההרכבים של הליגיונרים שלנו.</p></section><section className="desk-panel"><div className="desk-section-heading"><span>בהמשך היום</span><CalendarDays size={16}/></div>{upcoming.length?upcoming.map(m=><button className="upcoming-row" key={m.id} onClick={()=>p.openMatch(m)}><span className="upcoming-time">{clock(m.kickoff)}</span><span><strong>{displayName(m.home)}</strong><small>{displayName(m.away)}</small></span><Emblem name={m.home} id={m.homeId} src={m.homeBadge} small/></button>):<p className="rail-note">אין משחקים קרובים במידע הזמין לתאריך שבחרת.</p>}</section><section className="desk-panel"><div className="desk-section-heading"><span>הפינה שלך</span><Star size={16}/></div>{p.favorites.filter(f=>f.kind==='team').slice(0,4).map(f=><button className="rail-followed" key={f.id} onClick={()=>p.openFavorite(f)}><Emblem name={displayName(f.name)} id={f.id} small/><span>{displayName(f.name)}</span><ChevronLeft size={14}/></button>)}{!p.favorites.some(f=>f.kind==='team')&&<p className="rail-note">סמן קבוצות ומשחקים בכוכב, ורכז כאן את מה שמעניין אותך.</p>}<button className="rail-more" onClick={p.showFavorites}>למועדפים שלי<ArrowLeft size={14}/></button></section></aside>}
