"use client";
import { SportsDesktop } from "@/components/football/sports-desktop";
import { DesktopHero, DesktopLeagueRail, DesktopContentRail } from "@/components/football/desktop";
import { Legionnaires } from "@/components/football/legionnaires";
import { Globe2 } from "lucide-react";
import { IoFootballOutline, IoBasketballOutline } from "react-icons/io5";
import { displayName } from "@/lib/football/names";
import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import { Bell, CalendarDays, ChevronLeft, ChevronRight, Star, RefreshCw, Search, X, Trophy, ArrowUpRight, CircleDot } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { SidebarProvider, Sidebar } from "@/components/ui/sidebar";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { Match, League, Favorite, DayData } from "@/lib/football/types";
import { follows, isLive, isFinished, leagueName, countryName } from "@/lib/football/types";
import { useMatchNotifications, isQuietTime, useDesignMode, useFootball, useFavorites, useAlerts, detectAlerts, today, dayLabel, shiftDate, clock, useLiveDay, DAY_INTERVAL } from "@/lib/football/client";
import { MatchRow, FavoriteButton, Emblem, EmptyState, LoadingRows, CoverageNote } from "@/components/football/ui";
import { MatchDetail, type Panel } from "@/components/football/details";
import { LeagueDetail, TeamDetail } from "@/components/football/entity-pages";
import { NotificationPanel } from "@/components/football/notifications";
import { GoalToasts } from "@/components/football/goal-toasts";
const desktopMedia = "(min-width: 1050px)";
const subscribeDesktop = (callback: () => void) => { const media=window.matchMedia(desktopMedia);media.addEventListener("change",callback);return()=>media.removeEventListener("change",callback); };
type MainTab = "matches" | "leagues" | "favorites" | "legionnaires";
export default function Home() {
  const isDesktop=useSyncExternalStore(subscribeDesktop,()=>window.matchMedia(desktopMedia).matches,()=>false);
  const {demo,setDemo}=useDesignMode();
  const [legRefresh,setLegRefresh]=useState(0);
  const [tab, setTab] = useState<MainTab>("matches");
  const [sport,setSport]=useState<"Soccer"|"Basketball">("Soccer");
  const [date, setDate] = useState(today);
  const [query, setQuery] = useState("");
  const [debouncedQuery, setDebouncedQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [leagueLimit, setLeagueLimit] = useState(60);
  const [panel, setPanelState] = useState<Panel | null>(null);
  const [panelOpen,setPanelOpen]=useState(false);
  const panelHistory=useRef<{panel:Panel;scroll:number}[]>([]);
  const detailScroll=useRef<HTMLDivElement>(null);
  const restoreScroll=useRef(0);
  const tabScroll=useRef<Partial<Record<MainTab,number>>>({});
  const [tabDirection,setTabDirection]=useState("forward");
  const [direction,setDirection]=useState("forward");
  const setPanel=(next:Panel|null)=>{if(!next){setPanelOpen(false);panelHistory.current=[];return;}if(panelOpen&&panel){if(next.kind===panel.kind&&("id" in next?next.id:null)===("id" in panel?panel.id:null))return;panelHistory.current.push({panel,scroll:detailScroll.current?.scrollTop||0});}else panelHistory.current=[];restoreScroll.current=0;setDirection("forward");setPanelState(next);setPanelOpen(true);};
  const goBack=()=>{const previous=panelHistory.current.pop();if(previous){restoreScroll.current=previous.scroll;setDirection("back");setPanelState(previous.panel);}else setPanel(null);};
  useEffect(()=>{if(detailScroll.current)detailScroll.current.scrollTop=restoreScroll.current;},[panel]);
  useEffect(()=>{window.scrollTo({top:tabScroll.current[tab]||0,behavior:"instant"});},[tab]);
  const favorites = useFavorites(), alerts = useAlerts(), matchNotifications = useMatchNotifications();
  const liveDay = useFootball<DayData>({ view: "day", date: today(), tz: "Asia/Jerusalem" }, DAY_INTERVAL);
  const liveDayData = useLiveDay(liveDay.data, "Soccer", true);
  const otherDay = useFootball<DayData>(date !== today() ? { view: "day", date, tz: "Asia/Jerusalem" } : null);
  const basketballDay = useFootball<DayData>(sport === "Basketball" ? { view: "day", date, tz: "Asia/Jerusalem", sport: "Basketball" } : null, 120000);
  const dayResource = sport === "Basketball" ? basketballDay : date === today() ? liveDay : otherDay;
  const catalog = useFootball<{ leagues: League[]; limited: boolean }>({ view: "leagues" });
  const basketballCatalog = useFootball<{ leagues: League[]; limited: boolean }>(sport === "Basketball" ? { view: "leagues", sport: "Basketball" } : null);
  const search = useFootball<{ teams: { id: string; name: string; country: string; league: string; badge?:string }[] }>(debouncedQuery.length >= 2 ? { view: "search", q: debouncedQuery, sport } : null);
  useEffect(() => { const timer = setTimeout(() => setDebouncedQuery(query.trim()), 450); return () => clearTimeout(timer); }, [query]);
  const previous = useRef<Match[] | null>(null);
  useEffect(() => {
    const data = liveDayData;
    if (!data || data.liveState !== "connected") return;
    const before = previous.current;
    previous.current = data.matches;
    if (!before) return;
    const incoming = detectAlerts(before, data.matches, favorites.favorites, alerts.settings, data.fetchedAt, matchNotifications.values);
    if (!incoming.length) return;
    const added = alerts.add(incoming);
    if (!isQuietTime(alerts.settings) && alerts.settings.desktop && "Notification" in window && Notification.permission === "granted") for (const item of added) { try { new Notification(item.title, { body: item.body, tag: item.id, icon: "/favicon.svg" }); } catch { /* The in-app update remains available. */ } }
  }, [liveDayData, favorites.favorites, alerts, matchNotifications.values]);
  const basketballPrevious=useRef<Match[]|null>(null);
  useEffect(()=>{
    const data=basketballDay.data;
    if(!data||data.liveState!=="connected")return;
    const before=basketballPrevious.current;
    basketballPrevious.current=data.matches;
    if(!before)return;
    const incoming=detectAlerts(before,data.matches,favorites.favorites.filter(f=>(f.sport||"Soccer")==="Basketball"),alerts.settings,data.fetchedAt,matchNotifications.values,"Basketball");
    if(!incoming.length)return;
    const added=alerts.add(incoming);
    if(!isQuietTime(alerts.settings)&&alerts.settings.desktop&&"Notification" in window&&Notification.permission==="granted")for(const item of added){try{new Notification(item.title,{body:item.body,tag:item.id,icon:"/favicon.svg"})}catch{/* the in-app update remains available */}}
  },[basketballDay.data,favorites.favorites,alerts,matchNotifications.values]);
  const matches = dayResource.data?.matches || [];
  const cleanQuery = displayName(query.trim()).toLocaleLowerCase();
  const visibleMatches = matches.filter(m => (tab !== "favorites" || follows(m, favorites.favorites)) && (filter !== "live" || isLive(m.status)) && (filter !== "finished" || isFinished(m.status)) && (filter !== "followed" || favorites.has("match",m.id)) && (!cleanQuery || `${m.home} ${m.away} ${m.league} ${leagueName(m.league)} ${countryName(m.country)}`.toLocaleLowerCase().includes(cleanQuery)));
  const groups = new Map<string, Match[]>();
  for (const m of visibleMatches) groups.set(m.leagueId || m.league, [...(groups.get(m.leagueId || m.league) || []), m]);
  const sortedGroups = [...groups.entries()].sort((a, b) => Number(favorites.has("league", b[0])) - Number(favorites.has("league", a[0])));
  const allLeagues = (sport === "Basketball" ? basketballCatalog.data : catalog.data)?.leagues || [];
  const currentCatalog = sport === "Basketball" ? basketballCatalog : catalog;
  const filteredLeagues = allLeagues.filter(l => !cleanQuery || `${l.name} ${leagueName(l.name)} ${l.country} ${countryName(l.country)}`.toLocaleLowerCase().includes(cleanQuery));
  const openMatch = (m: Match) => setPanel({ kind: "match", id: m.id, name: `${m.home} – ${m.away}`, match: m, sport: m.sport === "Basketball" ? "Basketball" : "Soccer" });
  const changeTab = (next: MainTab) => { tabScroll.current[tab]=window.scrollY;const order=["matches","favorites","leagues","legionnaires"];setTabDirection(order.indexOf(next)>=order.indexOf(tab)?"forward":"back");setPanel(null); setTab(next); setQuery(""); setFilter("all"); setLeagueLimit(60); };
  const openSaved = (f: Favorite) => setPanel({ kind: f.kind, id: f.id, name: f.name, sport: f.sport });
  const unread = alerts.items.filter(a => !a.read).length;
  const activeTab=panelOpen ? panel?.kind === "alerts" ? "alerts" : panel?.kind === "league" ? "leagues" : panel?.kind === "team" ? "favorites" : "matches" : tab;
  const nav = <><button className={activeTab === "matches" ? "active" : ""} aria-current={activeTab==="matches"?"page":undefined} onClick={() => changeTab("matches")}>{sport==="Basketball"?<IoBasketballOutline size={22}/>:<IoFootballOutline size={22}/>}<span>משחקים</span></button><button className={activeTab === "favorites" ? "active" : ""} aria-current={activeTab==="favorites"?"page":undefined} onClick={() => changeTab("favorites")}><Star size={20}/><span>מועדפים</span></button><button className={activeTab === "leagues" ? "active" : ""} aria-current={activeTab==="leagues"?"page":undefined} onClick={() => changeTab("leagues")}><Trophy size={20}/><span>ליגות</span></button><button className={activeTab === "legionnaires" ? "active" : ""} aria-current={activeTab==="legionnaires"?"page":undefined} onClick={()=>changeTab("legionnaires")}><Globe2 size={20}/><span>ליגיונרים</span></button><button className={activeTab === "alerts" ? "active" : ""} aria-current={activeTab==="alerts"?"page":undefined} onClick={() => setPanel({ kind: "alerts" })}><span className="bell-wrap"><Bell size={20}/>{unread > 0 && <i/>}</span><span>התראות</span></button></>;
  const title = tab === "legionnaires" ? "ליגיונרים" : tab === "matches" ? "משחקים ותוצאות" : tab === "leagues" ? "ליגות וטורנירים" : "המועדפים שלי";
  const refresh = () => { if(tab==="legionnaires")setLegRefresh(v=>v+1); dayResource.retry(); if (tab === "leagues") currentCatalog.retry(); };
  const chooseSport = (next:"Soccer"|"Basketball") => { if(next===sport)return;setSport(next);setDate(today());setTab("matches");setFilter("all");setQuery("");setPanel(null); };
  const desktopProps={matches,leagues:allLeagues,favorites:favorites.favorites,openMatch,openLeague:(l:League)=>setPanel({kind:"league",id:l.id,name:leagueName(l.name)}),openFavorite:openSaved,has:favorites.has,toggle:favorites.toggle,showLeagues:()=>changeTab("leagues"),showFavorites:()=>changeTab("favorites"),showLegionnaires:()=>changeTab("legionnaires"),showLive:()=>{changeTab("matches");setFilter("live");},demo};
  return <>{isDesktop&&<div className="sport-desktop"><SportsDesktop footballDay={liveDayData} footballLeagues={allLeagues} footballLoading={liveDay.loading} footballError={liveDay.error} openMatch={openMatch} openLeague={l=>setPanel({kind:"league",id:l.id,name:leagueName(l.name)})} openAlerts={()=>setPanel({kind:"alerts"})} showLegionnaires={()=>changeTab("legionnaires")} openPanel={setPanel}/></div>}{!isDesktop&&<div className="app"><header className="topbar"><div className="top-inner"><button className="brand" onClick={() => changeTab("matches")} aria-label="kickoff — דף הבית"><img src="/brand/kickoff.png" alt=""/><span dir="ltr">kickoff</span></button><nav className="desktop-top-nav" aria-label="ניווט דסקטופ">{nav}</nav><div className="top-actions"><span className="header-note">הספורט שלך. בלי הפרעות.</span><button className="header-bell" onClick={() => setPanel({ kind: "alerts" })} aria-label={`התראות${unread ? `, ${unread} חדשות` : ""}`}><Bell size={20}/>{unread > 0 && <span>{unread > 9 ? "9+" : unread}</span>}</button></div></div></header>
    <div className={`mobile-sport-hero ${tab === "matches" ? "with-photo" : ""}`} data-sport={sport} dir="rtl"><div className="mobile-sport-photo" aria-hidden="true"/><div className="mobile-sport-inner"><div className="mobile-sport-intro"><strong>{tab === "matches" ? "כל הספורט במקום אחד" : title}</strong><span>{sport === "Soccer" ? "כדורגל" : "כדורסל"} · תוצאות ומשחקים</span></div><div className="mobile-sport-switch" role="group" aria-label="בחירת ענף"><button className={sport === "Soccer" ? "active" : ""} aria-pressed={sport === "Soccer"} onClick={()=>chooseSport("Soccer")}><IoFootballOutline/>כדורגל</button><button className={sport === "Basketball" ? "active" : ""} aria-pressed={sport === "Basketball"} onClick={()=>chooseSport("Basketball")}><IoBasketballOutline/>כדורסל</button></div></div></div>
    <SidebarProvider className="frame"><Sidebar collapsible="none" side="right" className="sidebar"><div className="desktop-league-rail"><DesktopLeagueRail {...desktopProps}/></div><div className="legacy-side"><p className="sidebar-title">המשחק מתחיל כאן</p><nav aria-label="ניווט ראשי">{nav}</nav><div className="side-favorites"><p className="sidebar-title">הליגות שלי</p>{favorites.favorites.filter(f => f.kind === "league").slice(0, 8).map(f => <button key={f.id} onClick={() => openSaved(f)}><Trophy size={15}/>{displayName(f.name)}</button>)}{!favorites.favorites.some(f => f.kind === "league") && <p>שמור ליגה בלחיצה על הכוכב.<br/>היא תחכה לך כאן.</p>}</div><p className="source">נתונים: <a href="https://www.thesportsdb.com" target="_blank" rel="noreferrer">TheSportsDB</a><br/>הכיסוי משתנה בין תחרויות.</p></div></Sidebar>
    <main key={tab} className={`main screen-enter page-${tabDirection}`} id="main-content">{tab==="matches"&&!query&&<DesktopHero showLive={desktopProps.showLive} showFavorites={desktopProps.showFavorites}/>}<div className="desktop-workspace"><div className="design-mode"><span>{demo ? "תצוגת עיצוב · נתוני המחשה" : dayResource.data?.limited === false ? (dayResource.data.liveState === "connected" ? "מחובר למקור נתונים חי" : "מקור נתונים מחובר · לייב לא זמין כרגע") : "מקור נתונים ציבורי · כיסוי חלקי"}</span><button onClick={()=>setDemo(!demo)}>{demo ? "לנתונים אמיתיים" : "צפה בעיצוב המלא"}</button></div><div className="heading"><div><p className="kicker">{sport === "Soccer" ? "כדורגל מכל העולם" : "כדורסל מכל העולם"}</p><h1>{title}</h1></div><button className="icon-button" onClick={refresh} aria-label="רענן נתונים"><RefreshCw size={18}/></button></div>
    {tab!=="legionnaires"&&<div className="tools"><label className="search"><Search size={19}/><input value={query} onChange={e => { setQuery(e.target.value); setLeagueLimit(60); }} placeholder="חיפוש קבוצה או ליגה" aria-label="חיפוש קבוצה או ליגה"/>{query && <button onClick={() => setQuery("")} aria-label="נקה חיפוש"><X size={16}/></button>}</label></div>}
    {cleanQuery.length >= 2 && <div className="search-results"><div className="section-subtitle">קבוצות <span>חיפוש בעברית או באנגלית</span></div>{search.loading ? <LoadingRows/> : search.error ? <div className="inline-error">החיפוש אינו זמין כרגע. <button onClick={search.retry}>נסה שוב</button></div> : search.data?.teams.length ? <div className="team-results">{search.data.teams.map(t => <div className="search-team" key={t.id}><button onClick={() => setPanel({ kind: "team", id: t.id, name: t.name, sport })}><Emblem name={t.name} id={t.id} src={t.badge} small/><span><strong>{t.name}</strong><small>{countryName(t.country)} · {leagueName(t.league)}</small></span></button><FavoriteButton item={{ kind: "team", id: t.id, name: t.name, sport }} saved={favorites.has("team", t.id)} toggle={favorites.toggle}/></div>)}</div> : <p className="muted small-copy">לא נמצאו קבוצות בשם הזה. אפשר לנסות את השם המלא.</p>}</div>}
    {tab === "matches" && sport === "Soccer" && !query && <button className="home-spotlight" onClick={()=>changeTab("legionnaires")}><span className="spotlight-copy"><small>הישראלים בחו״ל</small><strong>הליגיונרים שלנו</strong><span>שחקנים, משחקים והרכבים <ChevronLeft size={15}/></span></span><small className="spotlight-credit">איור · דמויות דמיוניות</small></button>}
    {tab === "favorites" && <section className="favorites-section"><div className="section-art"><img src="/brand/favorites-purple.webp" alt="שני כדורגלנים בדיוניים חוגגים יחד" loading="lazy" decoding="async"/><div><h2>הרגעים של הקבוצות שלך</h2><p>כל מה שבחרת לעקוב אחריו, במקום אחד.</p></div><small>תמונה מקורית · דמויות בדיוניות</small></div><div className="section-subtitle">המעקב שלי <span>נשמר במכשיר הזה</span></div>{favorites.favorites.some(f=>(f.sport||"Soccer")===sport) ? <><div className="favorites-strip">{favorites.favorites.filter(f=>f.kind==="team"&&(f.sport||"Soccer")===sport).map(f=><button key={f.id} onClick={()=>openSaved(f)}><Emblem name={displayName(f.name)} id={f.id} kind="team"/><span>{displayName(f.name)}</span></button>)}</div><div className="favorite-chips">{favorites.favorites.filter(f=>(f.sport||"Soccer")===sport).map(f => <div className="favorite-chip" key={`${f.kind}-${f.id}`}><button onClick={() => openSaved(f)}><span>{f.kind === "league" ? "ליגה" : f.kind === "team" ? "קבוצה" : "משחק"}</span><strong>{displayName(f.name)}</strong></button><FavoriteButton item={f} saved toggle={favorites.toggle}/></div>)}</div></> : <EmptyState title="בנה את רשימת המועדפים שלך" description="חפש קבוצה, בחר ליגה או פתח משחק ולחץ על הכוכב."/>}</section>}
    {tab === "legionnaires" ? <Legionnaires key={legRefresh} open={setPanel} matches={liveDayData?.matches||[]}/> : tab !== "leagues" ? <><div className="day-segments">{[[-1,"אתמול"],[0,"היום"],[1,"מחר"]].map(([n,label])=><button key={label} className={date===shiftDate(today(),Number(n))?"selected":""} onClick={()=>setDate(shiftDate(today(),Number(n)))}>{label}</button>)}</div><div className="mobile-daystrip" aria-label="בחירת יום">{[-2,-1,0,1,2].map(n=>{const d=shiftDate(date,n);const label=dayLabel(d,true).split(",");return <button key={d} className={d===date?"active":""} aria-pressed={d===date} onClick={()=>{setDate(d);setFilter("all")}}><span>{d===today()?"היום":label[0]}</span><strong>{label[1]?.trim()||d.slice(5)}</strong></button>})}</div><div className="datebar"><button onClick={() => { setDate(shiftDate(date, -1)); setFilter("all"); }} aria-label="יום קודם"><ChevronRight size={21}/></button><label className="date-picker"><CalendarDays size={18}/><span>{date === today() ? "היום" : dayLabel(date, true)}</span><input type="date" value={date} onChange={e => { if (e.target.value) { setDate(e.target.value); setFilter("all"); } }} aria-label="בחירת תאריך"/></label><button onClick={() => { setDate(shiftDate(date, 1)); setFilter("all"); }} aria-label="יום הבא"><ChevronLeft size={21}/></button>{date !== today() ? <button className="back-today" onClick={() => { setDate(today()); setFilter("all"); }}>להיום</button> : <span className="date-full">{dayLabel(date, true)}</span>}</div>
    <div className="filter-row"><Tabs value={filter} onValueChange={setFilter} dir="rtl"><TabsList className="filter-tabs"><TabsTrigger value="all"><span className="tab-label">הכל</span></TabsTrigger><TabsTrigger value="live"><span className="tab-label"><i className="live-dot"/>בלייב</span></TabsTrigger><TabsTrigger value="finished"><span className="tab-label">הסתיימו</span></TabsTrigger><TabsTrigger value="followed"><span className="tab-label"><Star size={14}/>במעקב</span></TabsTrigger></TabsList></Tabs><span className="timezone">שעון ישראל</span></div>
    {dayResource.data?.limited && <CoverageNote>תצוגה ראשונית עם נתונים חלקיים. התוצאות החיות יופעלו לאחר חיבור המנוי.</CoverageNote>}
    {date === today() && dayResource.data?.liveState === "unavailable" && <CoverageNote>החיבור החי מתעכב. התוצאות המוצגות עשויות להיות לא מעודכנות.</CoverageNote>}
    {dayResource.error && <div role="alert" className="inline-error">{dayResource.error} <button onClick={dayResource.retry}>נסה שוב</button></div>}
    {dayResource.data?.partial&&<CoverageNote>חלק מלוח המשחקים מתעכב. מוצגים הנתונים שהתקבלו; הרשימה תתעדכן אוטומטית.</CoverageNote>}{dayResource.loading ? <LoadingRows/> : sortedGroups.length ? <div className="groups" key={`${date}-${filter}`}>{sortedGroups.map(([id, games]) => { const first = games[0]; return <section className="group" key={id}><div className="group-header"><button onClick={() => first.leagueId && setPanel({ kind: "league", id: first.leagueId, name: leagueName(first.league), sport })}><Emblem name={leagueName(first.league)} id={first.leagueId} kind="league" src={first.leagueBadge}/><span><strong>{leagueName(first.league)}</strong><small>{countryName(first.country) || "תחרות כדורגל"}</small></span><ChevronLeft size={15}/></button>{first.leagueId && <FavoriteButton item={{ kind: "league", id: first.leagueId, name: leagueName(first.league), sport }} saved={favorites.has("league", first.leagueId)} toggle={favorites.toggle}/>}</div>{games.map(m => <MatchRow key={m.id} match={m} open={openMatch}/>)}</section>; })}</div> : !dayResource.error && <EmptyState title={filter === "live" && dayResource.data?.liveState !== "connected" ? "החיבור לתוצאות חיות עדיין אינו פעיל" : filter === "followed" ? "אין משחקים שסימנת בתאריך הזה" : tab === "favorites" ? "אין משחקים זמינים למועדפים בתאריך הזה" : cleanQuery ? "אין משחקים שתואמים לחיפוש" : filter === "live" ? "אין משחקים חיים במקור הנתונים כרגע" : "אין משחקים זמינים לתאריך הזה"} description="אפשר לבחור תאריך אחר או לעבור לרשימת הליגות."/>}
    </> : <><div className="section-subtitle">כל התחרויות <span>{filteredLeagues.length} תחרויות בקטלוג</span></div>{currentCatalog.loading ? <LoadingRows/> : currentCatalog.error ? <EmptyState title="רשימת הליגות לא נטענה" error description={currentCatalog.error} retry={currentCatalog.retry}/> : filteredLeagues.length ? <div className="league-list">{filteredLeagues.slice(0, leagueLimit).map(l => <div className="league-card" key={l.id}><button className="league-name" onClick={() => setPanel({ kind: "league", id: l.id, name: leagueName(l.name), sport })}><Emblem name={leagueName(l.name)} id={l.id} kind="league" src={l.badge}/><span><strong>{leagueName(l.name)}</strong><small>{countryName(l.country) || "ליגה / טורניר"}</small></span></button><FavoriteButton item={{ kind: "league", id: l.id, name: leagueName(l.name), sport }} saved={favorites.has("league", l.id)} toggle={favorites.toggle}/></div>)}</div> : <EmptyState title="לא נמצאו ליגות לחיפוש הזה"/>}{filteredLeagues.length > leagueLimit && <button className="plain-button load-more" onClick={() => setLeagueLimit(n => n + 60)}>הצג תחרויות נוספות</button>}<p className="catalog-note">הופעה בקטלוג אינה מבטיחה כיסוי חי, טבלאות או היסטוריה מלאה.</p></>}
    <footer className="main-footer"><span>{dayResource.data?.fetchedAt && tab !== "leagues" && tab !== "legionnaires" && `נתונים התקבלו ב־${clock(dayResource.data.fetchedAt)} · `}חינם למשתמשים · ללא פרסומות</span><a href="https://www.thesportsdb.com" target="_blank" rel="noreferrer">TheSportsDB <ArrowUpRight size={12}/></a></footer></div></main><DesktopContentRail {...desktopProps}/></SidebarProvider></div>}
    <Toaster position="top-center" dir="rtl" toastOptions={{className:"kickoff-toast"}}/>
    {isDesktop&&<GoalToasts matches={liveDayData?.matches} openMatch={openMatch} openSettings={()=>setPanel({kind:"alerts",tab:"settings"})}/>}
    {!isDesktop&&<nav className="mobile-nav bottom-navigation" aria-label="ניווט בנייד">{nav}</nav>}
    <Sheet open={panelOpen} onOpenChange={value => { if (!value) setPanel(null); }}><SheetContent side="left" className="detail-sheet" showCloseButton={false} dir="rtl"><div className="drawer-heading"><button className="back-button" onClick={goBack} aria-label="חזרה למסך הקודם"><ChevronRight size={20}/><span>חזרה</span></button><div><SheetDescription className="drawer-eyebrow">{panel?.kind === "match" ? "מרכז המשחק" : panel?.kind === "league" ? "ליגה / טורניר" : panel?.kind === "team" ? "הקבוצה" : "העדכונים שלך"}</SheetDescription><SheetTitle>{panel?.kind === "alerts" ? "מרכז ההתראות" : displayName(panel?.name || "פרטים")}</SheetTitle></div></div>{demo && <div className="demo-detail">נתוני המחשה · תצוגת עיצוב</div>}<div ref={detailScroll} key={panel?.kind === "alerts" ? "alerts" : `${panel?.kind}-${panel?.id}`} className={`detail-body screen-${direction}`}>{panel?.kind === "alerts" ? <NotificationPanel open={setPanel} liveState={liveDayData?.liveState} tab={panel.tab}/> : panel?.kind === "match" ? <MatchDetail key={`match-${panel.id}`} panel={panel} open={setPanel} has={favorites.has} toggle={favorites.toggle}/> : panel?.kind === "league" ? <LeagueDetail key={`league-${panel.id}`} panel={panel} open={setPanel} has={favorites.has} toggle={favorites.toggle}/> : panel?.kind === "team" ? <TeamDetail key={`team-${panel.id}`} panel={panel} open={setPanel} has={favorites.has} toggle={favorites.toggle}/> : null}</div><nav className="detail-nav bottom-navigation" aria-label="ניווט במסך פרטים">{nav}</nav></SheetContent></Sheet>
  </>;
}
