"use client";
import {displayResult} from "@/lib/football/names";
import { useState } from 'react';
import { Bell, BellRing, CheckCheck, Trash2, Check, Moon, Monitor, ArrowLeft, Flag, Radio, CircleDot, Clock3, Goal } from 'lucide-react';
import { GOAL_PREVIEW_EVENT } from './goal-toasts';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { useDesignMode, useAlerts, useFavorites, useMatchNotifications, useGoalToastSettings, clock, today, dayLabel } from '@/lib/football/client';
import type { AlertSettings, LiveState } from '@/lib/football/types';
import type { Panel } from './details';
const preferences=[{key:'goals',label:'שינויי תוצאה',sub:'שערים בכדורגל ונקודות בכדורסל',icon:CircleDot},{key:'kickoff',label:'שריקת הפתיחה',sub:'כשהמשחק מתחיל',icon:Flag},{key:'fulltime',label:'תוצאה סופית',sub:'כשהמשחק מסתיים',icon:CheckCheck}] as const;
const goalScopes=[{id:'top',label:'ליגות וטורנירים מובילים'},{id:'favorites',label:'רק מה שבמעקב'},{id:'all',label:'כל המשחקים'}] as const;
export function NotificationPanel({open,liveState,tab='feed'}:{open:(p:Panel)=>void;liveState?:LiveState;tab?:'feed'|'settings'}){
 const alerts=useAlerts(),favorites=useFavorites(),subscriptions=useMatchNotifications(),goalToasts=useGoalToastSettings();
 const [goalMessage,setGoalMessage]=useState('');
 async function enableGoalDesktop(){
  if(!('Notification' in window)){setGoalMessage('הדפדפן הזה אינו תומך בהתראות מערכת.');return;}
  try{const result=Notification.permission==='granted'?'granted':await Notification.requestPermission();goalToasts.update({desktop:result==='granted'});setGoalMessage(result==='granted'?'שערים יקפצו גם כהתראת מערכת כשהלשונית ברקע.':result==='denied'?'ההרשאה חסומה. ניתן לשנות זאת בהגדרות הדפדפן.':'');}catch{setGoalMessage('לא ניתן להפעיל כרגע התראות מערכת.');}
 }
 const {demo}=useDesignMode();
 const [filter,setFilter]=useState('all'),[permissionMessage,setPermissionMessage]=useState('');
 const unread=alerts.items.filter(a=>!a.read).length;
 const filtered=alerts.items.filter(a=>filter==='all'||filter==='unread'&&!a.read||filter==='goals'&&/שער|תוצאה/.test(a.title));
 const groups=new Map<string,typeof alerts.items>();
 for(const item of filtered){const d=new Date(item.at);const date=Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);groups.set(date,[...(groups.get(date)||[]),item]);}
 const change=(key:keyof AlertSettings,value:boolean)=>alerts.setSettings({...alerts.settings,[key]:value});
 async function enableDesktop(){
  if(!('Notification' in window)){setPermissionMessage('הדפדפן הזה אינו תומך בהתראות. העדכונים עדיין יופיעו כאן.');return;}
  try{const result=await Notification.requestPermission();change('desktop',result==='granted');setPermissionMessage(result==='granted'?'התראות הדפדפן הופעלו בזמן שהאתר פתוח.':result==='denied'?'ההרשאה חסומה. ניתן לשנות זאת בהגדרות הדפדפן.':'העדכונים ימשיכו להופיע במרכז ההתראות.');}catch{setPermissionMessage('לא ניתן להפעיל כרגע התראות דפדפן.');}
 }
 return <div className="notification-center notification-v2"><header className="inbox-hero"><div className="inbox-symbol"><BellRing size={25}/></div><div><span className="panel-eyebrow">העדכונים שלך</span><h2>{unread===1?'עדכון חדש מחכה לך':unread?`${unread} עדכונים מחכים לך`:'הכל מעודכן'}</h2><p>הרגעים החשובים מהמשחקים שלך.</p></div><span className={`connection-badge ${liveState==='connected'?'connected':''}`}><Radio size={13}/>{demo?'מצב המחשה':liveState==='connected'?'מחובר ללייב':'לייב לא זמין'}</span></header>
 <div className="inbox-summary"><span><strong>{favorites.favorites.filter(f=>f.kind==='team').length}</strong>קבוצות במעקב</span><span><strong>{Object.values(subscriptions.values).filter(v=>v&&typeof v==="object"?Object.values(v).some(Boolean):v===true).length}</strong>פעמוני משחק פעילים</span><span><strong>{alerts.items.length}</strong>עדכונים שמורים</span></div>
 <Tabs defaultValue={tab} dir="rtl" className="inbox-tabs"><TabsList className="detail-tab-list"><TabsTrigger value="feed"><span className="tab-label">העדכונים שלי</span></TabsTrigger><TabsTrigger value="settings"><span className="tab-label">העדפות התראות</span></TabsTrigger></TabsList>
 <TabsContent value="feed"><div className="inbox-toolbar"><div className="inbox-filters" aria-label="סינון התראות">{[['all','הכל'],['unread','לא נקראו'],['goals','שערים ותוצאות']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="inbox-actions"><button className="icon-button" onClick={()=>alerts.markRead()} disabled={!unread} aria-label="סמן הכל כנקרא" title="סמן הכל כנקרא"><CheckCheck size={17}/></button><button className="icon-button" onClick={alerts.clear} disabled={!alerts.items.length} aria-label="נקה עדכונים" title="נקה עדכונים"><Trash2 size={16}/></button></div></div>
 {filtered.length?<div className="inbox-groups">{[...groups].map(([date,items])=><section key={date}><h3 className="inbox-date">{date===today()?'היום':date?dayLabel(date,true):'עדכונים קודמים'}</h3>{items.map(item=>{const Icon=/שער|תוצאה/.test(item.title)?CircleDot:/סיום/.test(item.title)?Flag:Bell;return <button key={item.id} className={`inbox-item ${item.read?'read':'unread'}`} onClick={()=>{alerts.markRead(item.id);open({kind:'match',id:item.matchId,name:'מרכז המשחק',sport:item.sport});}}><span className="inbox-event-icon"><Icon size={20}/></span><span className="inbox-item-copy"><span className="inbox-item-heading"><strong>{item.title}</strong><time>{clock(item.at)}</time></span><span className="inbox-result">{displayResult(item.body)}</span><span className="inbox-open">למרכז המשחק<ArrowLeft size={12}/></span></span>{!item.read&&<i className="unread-marker" aria-label="לא נקרא"/>}</button>})}</section>)}</div>:<div className="inbox-empty"><Bell size={30}/><h3>{filter==='unread'?'קראת את כל העדכונים':filter==='goals'?'אין עדכוני שערים כרגע':'מחכים לרגע הבא'}</h3><p>לחץ על הפעמון במרכז המשחק כדי לקבל כאן עדכונים. קבוצות וליגות שבמועדפים נכללות גם הן.</p></div>}
 <div className="inbox-footnote"><Clock3 size={15}/><span>עדכונים מתקבלים כל עוד האתר פתוח, בהתאם לזמינות הספק.</span></div></TabsContent>
 <TabsContent value="settings"><div className="preferences-heading"><div><h3>מה תרצה לקבל?</h3><p>ברירות המחדל שלך. אפשר לבחור עדכונים אחרים בפעמון של כל משחק.</p></div><span><Check size={13}/>נשמר אוטומטית</span></div>
 <div className="preferences-card goal-toast-card"><div className="preference-row"><span className="preference-icon goal"><Goal size={19}/></span><label htmlFor="pref-goal-toast"><strong>גול קופץ על המסך</strong><small>כמו בטלוויזיה: הדקה, התוצאה וחץ לעבר הקבוצה שהבקיעה</small></label><Switch id="pref-goal-toast" dir="ltr" checked={goalToasts.settings.enabled} onCheckedChange={v=>goalToasts.update({enabled:v})}/></div>
 {goalToasts.settings.enabled&&<><div className="goal-scope" role="radiogroup" aria-label="מאילו משחקים">{goalScopes.map(s=><button key={s.id} type="button" role="radio" aria-checked={goalToasts.settings.scope===s.id} className={goalToasts.settings.scope===s.id?'selected':''} onClick={()=>goalToasts.update({scope:s.id})}>{s.label}</button>)}</div>
 <div className="preference-row"><span className="preference-icon"><Monitor size={19}/></span><div className="preference-copy"><strong>גם כהתראת מערכת</strong><small>כשהאתר פתוח בלשונית ברקע</small></div><Switch dir="ltr" checked={goalToasts.settings.desktop} onCheckedChange={v=>v?void enableGoalDesktop():goalToasts.update({desktop:false})} aria-label="התראת מערכת לשערים"/></div>
 <div className="goal-preview-row"><small>{goalToasts.settings.scope==='top'?'הפרמייר ליג, לה ליגה, הליגות הגדולות, ליגת העל, ליגת האלופות, נבחרות וטורנירים. קבוצות במעקב תמיד נכללות.':goalToasts.settings.scope==='favorites'?'רק קבוצות, ליגות ומשחקים שסימנת בכוכב.':'כל שער בכל משחק חי. עלול להיות עמוס בשעות העומס.'}</small><button type="button" className="plain-button" onClick={()=>window.dispatchEvent(new Event(GOAL_PREVIEW_EVENT))}>הצג דוגמה</button></div></>}
 {goalMessage&&<p role="status" className="permission-message">{goalMessage}</p>}</div>
 <div className="preferences-card">{preferences.map(({key,label,sub,icon:Icon})=><div className="preference-row" key={key}><span className="preference-icon"><Icon size={19}/></span><label htmlFor={`pref-${key}`}><strong>{label}</strong><small>{sub}</small></label><Switch id={`pref-${key}`} dir="ltr" checked={alerts.settings[key]} onCheckedChange={v=>change(key,v)}/></div>)}</div>
 <div className="preferences-card"><div className="preference-row"><span className="preference-icon"><Moon size={19}/></span><label htmlFor="pref-quiet"><strong>שעות שקטות</strong><small>השתקת התראות דפדפן בשעות שתבחר</small></label><Switch id="pref-quiet" dir="ltr" checked={!!alerts.settings.quiet} onCheckedChange={v=>change('quiet',v)}/></div>{alerts.settings.quiet&&<div className="quiet-times"><label>משעה<input type="time" value={alerts.settings.quietFrom||'23:00'} onChange={e=>alerts.setSettings({...alerts.settings,quietFrom:e.target.value})}/></label><label>עד שעה<input type="time" value={alerts.settings.quietTo||'07:00'} onChange={e=>alerts.setSettings({...alerts.settings,quietTo:e.target.value})}/></label><small>שעון ישראל</small></div>}</div>
 <div className="preferences-card"><div className="preference-row"><span className="preference-icon"><Monitor size={19}/></span><div className="preference-copy"><strong>התראות בדפדפן</strong><small>{alerts.settings.desktop?'מופעלות בזמן שהאתר פתוח':'עדכונים גם כשאתה בלשונית אחרת'}</small></div><button className="plain-button" onClick={()=>alerts.settings.desktop?change('desktop',false):void enableDesktop()}>{alerts.settings.desktop?'כיבוי':'הפעלה'}</button></div><p className="preference-note">כשהאתר סגור לא נשלחות התראות. העדפות אלו נשמרות במכשיר הזה.</p></div>{permissionMessage&&<p role="status" className="permission-message">{permissionMessage}</p>}
 <details className="notification-coverage"><summary>אילו עדכונים זמינים?</summary><p>שערים, שינויי תוצאה, פתיחה וסיום — לפי נתוני הלייב המתקבלים. התראות על הרכבים וכרטיסים אדומים עדיין אינן פעילות. סימון כוכב שומר משחק; הפעמון מפעיל או משתיק את העדכונים שלו.</p></details></TabsContent></Tabs></div>;
}
